name: CI Workflow

on: [pull_request]

jobs:
  Check:
    name: Build Checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: nodeJS unit test
        run: |
          npm i
          npm run test
          
  AddLabel:
    name: Add Label
    runs-on: ubuntu-latest
    needs: [Check]
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/label.yml
